### ISSUE TITLE
install.xml issue

### ISSUE THREAD

**Issue by danmarsden** [CharityLearning/moodle-mod_clearlesson#10]
on fresh install:
XMLDB has detected one TEXT/BINARY column (type) with some DEFAULT defined. This type of columns cannot have any default value. Please fix it in source (XML and/or upgrade script) to avoid this message to be displayed.
line 1727 of /lib/datalib.php: call to debugging()
line 352 of /lib/xmldb/xmldb_object.php: call to xmldb_debug()
line 261 of /lib/xmldb/xmldb_field.php: call to xmldb_object->debug()
line 359 of /lib/xmldb/xmldb_field.php: call to xmldb_field->setDefault()

**Comment by joshwillcock** [comment]
Thankyou for this Dan,

The Travis recommendation also has been very helpful
