### ISSUE TITLE
repo name "clearlessons" -> "clearlesson"

### ISSUE THREAD

**Issue by danmarsden** [CharityLearning/moodle-mod_clearlesson#9]
you might want to remove the "s" from the github repo name - I just downloaded and tried to install into a folder called "clearlessons" and was wondering why I was getting all the failure messages :-)

**Comment by joshwillcock** [comment]
Thanks for spotting this. This comes down to a 'branding issue'. The platform is called "Clear Lessons" however an individual resource would be a "Clear Lesson Video" - Clear Lessons Video sounds odd... We'll focus on Singular for the plugin as it's a single resource.
